config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from utils import views

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ficheros/', include(('ficheros.urls', 'ficheros'), namespace='ficheros')),
    path('contratos/', include(('contratos.urls', 'contratos'), namespace='contratos')),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

firmatec/ficheros/urls.py
"""Ficheros urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from ficheros import views


urlpatterns = [
    # Management
    path(
        route='',
        view=views.FicheroListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.FicheroListView.as_view(),
        name='list'
    ),
    path(
        route='<int:fichero_id>/update/',
        view=views.update_fichero,
        name="update"
    ),
    path(
        route='create',
        view=views.create_fichero,
        name="create"
    ),
    path(
        route='<int:fichero_id>/detail/',
        view=views.detail_fichero,
        name="detail"
    ),
    path(
        route='<int:object_id>/delete/',
        view=views.delete_fichero,
        name="delete"
    ),
]

firmatec/urls.py
""" from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
] """
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

firmatec/users/urls.py
"""Users urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views


urlpatterns = [
    # Management
    path(
        route='signin/',
        view=views.SignInView.as_view(),
        name='signin'
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(next_page='/users/signin/'),
        name='logout'
    ),
    path(
        route='',
        view=views.UserListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.UserListView.as_view(),
        name='list'
    ),
    path(
        route='<int:user_id>/update/',
        view=views.update_user,
        name="update"
    ),
    path(
        route='create',
        view=views.create_user,
        name="create"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    path(
        route='change_password/',
        view=views.PasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='admin/<int:user_id>/change_password/',
        view=views.admin_change_password,
        name='admin_change_password'
    ),
    path(
        route='<int:user_id>/contrato/',
        view=views.generar_contrato_usuario,
        name='generar_contrato'
    )
]

firmatec/users/models/users.py
"""User model."""

# Django
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

#Utilities
from utils.models import BaseModel, Planta
# from users import User, Sexo, Civil, Nacionalidades, SistemaSalud, SistemaPrevision, Banco, TipoCta
# atributos, cambiar_clave, codigo, email, rut, sexo, estado_civil, fecha_nac, telefono,
# nacionalidades, domicilio, planta, sistema_salud, sistema_prevision, banco, tipo_cta, cuenta


class Sexo(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este sexo, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Civil(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este estado civil, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Nacionalidades(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True,
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar esta nacionalidad, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class SistemaSalud(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este Sistema de Salud, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class SistemaPrevision(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este estado Sistema de Prevision, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Banco(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este banco, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )

class TipoCta(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este tipo de cuenta, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User, change the username field
    to rut and add some extra fields.
    """
    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    atributos = models.JSONField(blank=True, null=True)

    cambiar_clave = models.BooleanField(
        'Cambiar Clave',
        default=True,
        help_text='Marque esta casilla para que el usuario cambie su clave después de ingresar.'
    )

    codigo = models.CharField(
        'código',
        help_text='Identificador único del sistema de gestión.',
        max_length=6,
        unique=True,
        blank=True,
        null=True
    )

    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con este email registrado.'
        }
    )

    planta = models.ManyToManyField(
        Planta,
        help_text='Seleccione una o mas plantas a las que pertenecerá el usuario.'
    )

    rut_regex = RegexValidator(
        regex=r'^[0-9]{7,9}[0-9kK]{1}$',
        message='El RUT debe ser valido. Ingresalo sin puntos ni guiones.'
    )

    rut = models.CharField(
        max_length=12,
        validators=[rut_regex, ],
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con este RUT registrado.'
        }
    )

    sexo = models.ForeignKey(Sexo, on_delete=models.PROTECT, null=True, blank=True)

    estado_civil = models.ForeignKey(Civil, on_delete=models.PROTECT, null=True, blank=True)

    fecha_nac = models.DateField(null=True, blank=True)

    telefono_regex = RegexValidator(
        regex=r'\+?1?\d{9,15}$',
        message='El numero de telefono debe ser ingresado en el siguiente formato +999999999. Solo puede ingresar hasta 15 digitos.'
    )

    telefono = models.CharField(
        'Teléfono',
        validators=[telefono_regex, ],
        max_length=15,
        blank=True,
        null=True
    )

    nacionalidades = models.ForeignKey(Nacionalidades, on_delete=models.PROTECT, null=True, blank=True)

    domicilio = models.CharField(
        max_length=200,
        null=True,
        blank=True
    )

    sistema_salud = models.ForeignKey(SistemaSalud, on_delete=models.PROTECT, null=True, blank=True)

    sistema_prevision = models.ForeignKey(SistemaPrevision, on_delete=models.PROTECT, null=True, blank=True)

    banco = models.ForeignKey(Banco, on_delete=models.PROTECT, null=True, blank=True)

    tipo_cta = models.ForeignKey(TipoCta, on_delete=models.PROTECT, null=True, blank=True)

    cuenta = models.CharField(
        'Número de cuenta',
        max_length=30,
        blank=True,
        unique=True,
        null=True
    )

    def __str__(self):
        """Return RUT."""
        return self.rut

    def get_short_name(self):
        """Return RUT."""
        return self.rut

firmatec/users/forms.py
"""Users Forms"""

# Django
from django import forms
from django.forms import inlineformset_factory, RadioSelect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
# Firmatec Model
from utils.models import Planta
#from users.models import Sexo, Civil

User = get_user_model()


class CrearUsuarioForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             widget=forms.EmailInput(attrs={'class': "form-control-lg"}))
    first_name = forms.CharField(required=True, label="Nombres",
                                 widget=forms.TextInput(attrs={'class': "form-control-lg"}))
    last_name = forms.CharField(required=True, label="Apellidos",
                                widget=forms.TextInput(attrs={'class': "form-control-lg"}))
    group = forms.ModelChoiceField(queryset=Group.objects.none(), required=True, label="Perfil",
                                   widget=forms.Select(attrs={'class': 'selectpicker show-tick form-control-lg',
                                                              'data-size': '5',
                                                              'data-live-search': 'true',
                                                              'data-live-search-normalize': 'true'
                                                              })
                                   )
    plantas = forms.ModelMultipleChoiceField(queryset=Planta.objects.none(), required=True, label="Plantas",
                                            widget=forms.SelectMultiple(
                                                attrs={'class': 'selectpicker show-tick form-control-lg',
                                                       'data-size': '5',
                                                       'data-live-search': 'true',
                                                       'data-live-search-normalize': 'true'
                                                       })
                                            )
    planta = forms.ModelChoiceField(queryset=Planta.objects.none(), required=True, label="Planta",
                                   widget=forms.Select(attrs={'class': 'selectpicker show-tick form-control-lg',
                                                              'data-size': '5',
                                                              'data-live-search': 'true',
                                                              'data-live-search-normalize': 'true'
                                                              })
                                   )

    rut = forms.CharField(required=True, label="RUT",
                          widget=forms.TextInput(attrs={'class': "form-control-lg"}))

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CrearUsuarioForm, self).__init__(*args, **kwargs)
        if user.groups.filter(name='Trabajador'):
            self.fields.pop('plantas')
        if not user.groups.filter(name='Administrador').exists():
            self.fields['group'].queryset = Group.objects.exclude(name__in=['Administrador', ])
            self.fields['planta'].queryset = Planta.objects.filter(id__in=user.planta.all())
        else:
            self.fields['group'].queryset = Group.objects.all()
            self.fields['plantas'].queryset = Planta.objects.all()
            self.fields['planta'].queryset = Planta.objects.all()


    class Meta:
        model = User
        fields = ("first_name", "last_name", "sexo", "rut", "email", "telefono", "estado_civil", "fecha_nac", 
                  "nacionalidades", "domicilio", "sistema_salud", "sistema_prevision", "banco", "tipo_cta",
                  "cuenta", "group", "planta", "is_active", )
        exclude = ('password1', 'password2')


class EditarUsuarioForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             widget=forms.EmailInput(attrs={'class': "form-control-lg"}))
    first_name = forms.CharField(required=True, label="Nombres",
                                 widget=forms.TextInput(attrs={'class': "form-control-lg"}))
    last_name = forms.CharField(required=True, label="Apellidos",
                                widget=forms.TextInput(attrs={'class': "form-control-lg"}))
    group = forms.ModelChoiceField(queryset=Group.objects.none(), required=True, label="Perfil",
                                   widget=forms.Select(attrs={'class': 'selectpicker show-tick form-control-lg',
                                                              'data-size': '5',
                                                              'data-live-search': 'true',
                                                              'data-live-search-normalize': 'true'
                                                              })
                                   )
    planta = forms.ModelMultipleChoiceField(queryset=Planta.objects.none(), required=True, label="Planta",
                                            widget=forms.SelectMultiple(
                                                attrs={'class': 'selectpicker show-tick form-control-lg',
                                                       'data-size': '5',
                                                       'data-live-search': 'true',
                                                       'data-live-search-normalize': 'true'
                                                       })
                                            )
    rut = forms.CharField(required=True, label="RUT",
                          widget=forms.TextInput(attrs={'class': "form-control-lg"}))

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(EditarUsuarioForm, self).__init__(*args, **kwargs)
        if not user.groups.filter(name='Administrador').exists():
            self.fields['group'].queryset = Group.objects.exclude(name__in=['Administrador', ])
            self.fields['planta'].queryset = Planta.objects.filter(id__in=user.planta.all())
        else:
            self.fields['group'].queryset = Group.objects.all()
            self.fields['planta'].queryset = Planta.objects.all()

    class Meta:
        model = User
        fields = ("first_name", "last_name", "sexo", "rut", "email", "telefono", "estado_civil", "fecha_nac", 
                  "nacionalidades", "domicilio", "sistema_salud", "sistema_prevision", "banco", "tipo_cta",
                  "cuenta", "group", "planta", "is_active", )

firmatec/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

firmatec/templates/users/users_detail.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}
{% block page_title %}Usuarios{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'admin/assets/plugins/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
  <li class="breadcrumb-item"><a href="javascript:;">Inicio</a></li>
  <li class="breadcrumb-item"><a href="javascript:;">Usuarios</a></li>
  <li class="breadcrumb-item active">Detalle</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Usuarios <small>Detalle</small></h1>
<!-- end page-header -->

<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
      {% if usuario.last_login %}
      <span class="panel-title" style="font-style: italic;">
        Ultimo acceso el:
        <strong>{{ usuario.last_login|date:'d/M/Y' }}</strong>
      </span>
      {% endif %}
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
    </div>
    <h4 class="panel-title">
      {{ usuario.first_name|upper }} {{ usuario.last_name|upper }}</h4>
  </div>
  <div class="panel-body">

    <form method="post" autocomplete="off" novalidate>
      {% csrf_token %}
      <div class="form-group">
        <label for="id_first_name">Nombres:</label>
        <div class="form-control">{{ usuario.first_name|lower|title }}</div>
        <!-- <div class="form-control-lg">{{ usuario.first_name|lower|title }}</div> -->
      </div>
      <div class="form-group">
        <label for="id_first_name">Apellidos:</label>
        <div class="form-control">{{ usuario.last_name|lower|title }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Sexo:</label>
        <div class="form-control">{{ usuario.sexo.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">RUT:</label>
        <div class="form-control">{{ usuario.rut|rut_format }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Email:</label>
        <div class="form-control">{{ usuario.email|lower }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Teléfono:</label>
        <div class="form-control">{{ usuario.telefono }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Estado Civil:</label>
        <div class="form-control">{{ usuario.estado_civil.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Fecha Nac:</label>
        <div class="form-control">{{ usuario.fecha_nac|lower|title }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Nacionalidads:</label>
        <div class="form-control">{{ usuario.nacionalidades.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Domicilio:</label>
        <div class="form-control">{{ usuario.domicilio|lower|title }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Sistema Salud:</label>
        <div class="form-control">{{ usuario.sistema_salud.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Sistema Prevision:</label>
        <div class="form-control">{{ usuario.sistema_prevision.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Banco:</label>
        <div class="form-control">{{ usuario.banco.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Tipo de Cuenta:</label>
        <div class="form-control">{{ usuario.tipo_cta.nombre|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Número de cuenta:</label>
        <div class="form-control">{{ usuario.cuenta|lower|title }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Perfil:</label>
        <div class="form-control">{{ usuario.groups.first.name|upper }}</div>
      </div>
      <div class="form-group">
        <label for="id_first_name">Plantas:</label>
        <ul>
          {% for p in usuario.planta.all %}
            <li style="font-size: large;">{{ p.nombre|title }}</li>
          {% empty %}
            <li style="font-size: large;">Sin plantas asignadas</li>
          {% endfor %}
        </ul>
      </div>
      <div class="form-group">
        {% if usuario.is_active %}
        <div class="col-md-6 form-control-lg text-center">
          {% if usuario.id == request.user.id %}
          <a href="{% url 'users:change_password' %}" class="btn btn-md btn-warning">
            <i class="fas fa-lg fa-key"></i> Cambiar Clave</a>
          {% comment %}{% else %}
            {% if user.groups.first.name == 'Administrador' or user.groups.first.name == 'Administrador Contratos'  %}
              <a href="{% url 'users:admin_change_password' usuario.id %}" class="btn btn-warning">
                <i class="fas fa-lg fa-key"></i> Cambiar Clave</a>
            {% endif %}{% endcomment %}
          {% endif %}
        </div>
      {% endif %}
        <div class="col-md-6 offset-md-6 text-right">
          {{ usuario.is_active|tag_active_detail|safe }}
          <small class="form-text text-muted">Indica si el usuario debe ser tratado como activo. Desmarque esta opción en lugar de borrar la cuenta.</small>
        </div>
      </div>

      <div class="form-group row m-b-0">
        <div class="col-md-4 col-sm-4 col-form-label">
          <button class="btn btn-warning btn-ver-contrato"
                  data-id="{{ usuario.id }}">
              <i class="fas fa-list-alt"></i> Generar Contrato
          </button>
        </div>

        <div class="col-md-8 col-sm-8 text-right">
          {% if perms.user.add_user %}
            <a href="{% url 'users:list' %}?page={{ request.GET.page }}" class="btn btn-default">Volver</a>
          {% else %}
            <a href="{% url 'home' %}" class="btn btn-default">Volver</a>
          {% endif %}
          {% if user.groups.first.name == 'Administrador' or user.groups.first.name == 'Administrador Contratos'  %}
            <a href="{% url 'users:update' usuario.id %}?page={{ request.GET.page }}" class="btn btn-success">Editar</a>
          {% endif %}
        </div>
      </div>
    </form>
  </div>
</div>
<div class="modal fade" id="modal-usuario">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<!-- end panel -->
{% endblock %}
{% block librerias %}
    <script src="{% static 'admin/assets/plugins/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'admin/assets/plugins/bootstrap-select/js/i18n/defaults-es_CL.min.js' %}"></script>
    <!-- jquery validation -->
    <script src="{% static "admin/assets/plugins/jquery-validation/dist/jquery.validate.min.js" %}"></script>
    <script src="{% static "admin/assets/plugins/jquery-validation/dist/localization/messages_es_PE.min.js" %}"></script>
{% endblock %}

{% block scripts %}
  var contratosUrl = '/contratos/';

  $('.btn-ver-contrato').on('click', function(e){
        e.preventDefault();
        var id = $(this).data('id');
        console.log('usuario_id', 'id');
        var URL = '/users/'+id+'/contrato/';

        console.log('URL', URL);

        $.ajax({
              url: URL,
              type: 'get',
              dataType: 'json',
              beforeSend: function () {
                $("#modal-usuario").modal("show");
              },
              success: function (data) {
                  $("#modal-usuario .modal-content").html(data.html_form);
              }
            });
    });

  $("#modal-usuario").on("submit", ".js-generar-contrato-form", function () {
      var form = $(this);
      var $boton = $('.btn-modal-submit');

      $('.msg-loading').show('slow');

      $boton.prop('disabled', true);
      $boton.addClass('disabled');

      $.ajax({
        url: form.attr("action"),
        data: form.serialize(),
        type: form.attr("method"),
        dataType: 'json',
        success: function (data) {
          $('.msg-loading').hide();
          $('.btn-modal-submit').hide();

          if (data.form_is_valid) {
              console.log('Form Valid');
              //$("#modal-usuario").modal("hide");
              $('.success-msg-box').html(data.mensaje);
              $('.msg-success').show('slow');

              $('#modal-usuario').on('click', '.success-link', function(e){
                e.preventDefault();
                window.location.href = contratosUrl + data.id_contrato + '/detail/';
              });

              iziToast.success({
                  title: '',
                  message: 'Contrato generado exitosamente.',
                  position: 'topRight',
              });
          }
          else {
              console.log('Error');
              console.log(data.mensaje);
              $('.msg-box').html(data.mensaje);
              $('.msg-error').show('slow');
          }
        }
      });
      return false;
  });
  {% if messages %}
        console.log('mensajes');
        {% for mensaje in messages %}
            console.log("{{ mensaje.tags}}"+" "+"{{ mensaje }}");
            {% if mensaje.tags == 'success' %}
              iziToast.success({
                  message: '{{ mensaje }}',
                  position: 'topRight',
              });
            {% elif mensaje.tags == 'error' %}
              iziToast.error({
                  message: '{{ mensaje }}',
                  position: 'topRight',
              });
            {% endif %}
        {% endfor %}

    {% endif %}
{% endblock %}

firmatec/templates/users/users_generar_contrato.html
<form method="post" action="{% url 'users:generar_contrato' user_id=usuario.id %}"
      class="js-generar-contrato-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Generar Contrato</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
  <div class="modal-body">
    <div class="text-center">
      Desea generar el set de contrato de:
      <p style="font-weight: bold;">{{ usuario.first_name|upper }} {{ usuario.last_name|upper }}</p>
    </div>
    <div class="msg-loading text-center"  style="display: none;">
      <div class="fa-2x">
        <i class="fas fa-spinner fa-pulse"></i>
      </div>
      <span class="text-black-darker" style="font-style: italic;">Generando Documentos...</span>

    </div>
    <div class="msg-error" style="display: none;">
      <div class="alert alert-warning fade show">
          <i class="fas fa-exclamation-circle m-r-2"></i><strong>No se puede generar el contrato</strong>
          <p class="msg-box text-black-darker">Aqui va el mensaje.</p>
      </div>
    </div>
    <div class="msg-success" style="display: none;">
      <div class="alert alert-success fade show">
          <p class="text-black-darker">
            <i class="fas fa-check m-r-5"></i><strong>Contrato generado</strong>
            <span class="success-msg-box">Aqui va el mensaje.</span>
            <a href="javascript:;" class="alert-link success-link">aquí</a>. </p>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
    <button type="submit" class="btn btn-warning btn-modal-submit">Generar</button>
  </div>
</form>