config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from utils import views

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ficheros/', include(('ficheros.urls', 'ficheros'), namespace='ficheros')),
    path('contratos/', include(('contratos.urls', 'contratos'), namespace='contratos')),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

firmatec/contratos/urls.py
"""Contratos urls."""

#Django
from django.urls import path
from contratos import views


urlpatterns = [
    path(
        route='plantilla/list/',
        view=views.PlantillaListView.as_view(),
        name="list-plantilla"
    ),
    path(
        route='plantilla/create/',
        view=views.create_plantilla,
        name="create-plantilla"
    ),
    path(
        route='<int:plantilla_id>/plantilla/update/',
        view=views.update_plantilla,
        name="update-plantilla"
    ),
    path(
        route='<int:object_id>/plantilla/delete/',
        view=views.delete_plantilla,
        name="delete-plantilla"
    ),
    path(
        route='list/',
        view=views.ContratoListView.as_view(),
        name="list"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.ContratoDetailView.as_view(),
        name="detail"
    ),

]

firmatec/ficheros/urls.py
"""Ficheros urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from ficheros import views


urlpatterns = [
    # Management
    path(
        route='',
        view=views.FicheroListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.FicheroListView.as_view(),
        name='list'
    ),
    path(
        route='<int:fichero_id>/update/',
        view=views.update_fichero,
        name="update"
    ),
    path(
        route='create',
        view=views.create_fichero,
        name="create"
    ),
    path(
        route='<int:fichero_id>/detail/',
        view=views.detail_fichero,
        name="detail"
    ),
    path(
        route='<int:object_id>/delete/',
        view=views.delete_fichero,
        name="delete"
    ),
]

firmatec/urls.py
""" from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
] """
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

firmatec/users/urls.py
"""Users urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views


urlpatterns = [
    # Management
    path(
        route='signin/',
        view=views.SignInView.as_view(),
        name='signin'
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(next_page='/users/signin/'),
        name='logout'
    ),
    path(
        route='',
        view=views.UserListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.UserListView.as_view(),
        name='list'
    ),
    path(
        route='<int:user_id>/update/',
        view=views.update_user,
        name="update"
    ),
    path(
        route='create',
        view=views.create_user,
        name="create"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    path(
        route='change_password/',
        view=views.PasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='admin/<int:user_id>/change_password/',
        view=views.admin_change_password,
        name='admin_change_password'
    ),
    path(
        route='<int:user_id>/contrato/',
        view=views.generar_contrato_usuario,
        name='generar_contrato'
    )
]

firmatec/contratos/models/contratos.py
"""Contratos model."""
import os

from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
# Models
from users.models import User
# Utilities
from utils.models import BaseModel
User = get_user_model()


class Contrato(BaseModel):
    POR_FIRMAR = 'PF'
    FIRMADO_TRABAJADOR = 'FT'
    FIRMADO_EMPLEADOR = 'FE'
    FIRMADO = 'FF'
    OBJETADO = 'OB'

    CONTRATO_ESTADO = (
        (POR_FIRMAR, 'Por Firmar'),
        (FIRMADO_TRABAJADOR, 'Firmado por Trabajador'),
        (FIRMADO_EMPLEADOR, 'Firmado por Empleador'),
        (FIRMADO, 'Firmado'),
        (OBJETADO, 'Objetado'),
    )

    archivado = models.BooleanField(default=False)
    estado = models.CharField(max_length=2, choices=CONTRATO_ESTADO, default=POR_FIRMAR)
    obs = models.TextField(blank=True, null=True)

    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.usuario.rut) + '-' +str(self.id).zfill(4)


def contrato_directory_path(instance, filename):
    return '/'.join(['contratos', str(instance.contrato.usuario.id), filename])


class DocumentosContrato(BaseModel):
    archivo = models.FileField(upload_to=contrato_directory_path,
                               validators=[
                                   FileExtensionValidator(allowed_extensions=['pdf', ])])
    contrato = models.ForeignKey(Contrato, on_delete=models.CASCADE)

    class Meta:
        ordering = ['contrato']
        verbose_name = "Documento"
        verbose_name_plural = "Documentos"

    def __str__(self):
        return str(self.contrato.usuario) + '-' + self.nombre_archivo

    @property
    def nombre_archivo(self):
        return os.path.basename(self.archivo.name)

firmatec/contratos/models/plantillas.py
"""Plantillas model."""

from django.db import models
from django.core.validators import FileExtensionValidator
# Mailmerge
from mailmerge import MailMerge
#Utilities
from utils.models import BaseModel, Planta


class Tipo(BaseModel):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']


class Plantilla(BaseModel):
    activo = models.BooleanField(default=True)
    archivo = models.FileField(
        upload_to='plantillas/',
        validators=[FileExtensionValidator(allowed_extensions=['doc', 'docx', ])]
    )
    nombre = models.CharField(max_length=120)
    plantas = models.ManyToManyField(Planta)
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre

    def codigo(self):
        return str(self.pk).zfill(4)

    @property
    def atributos(self):
        documento = MailMerge(self.archivo)
        atributos = documento.get_merge_fields()
        return atributos

firmatec/ficheros/models.py
from django.db import models

# Create your models here.
"""Django models utilities."""

import os
# Django
# from django.db import models
from django.core.validators import FileExtensionValidator
#Utilities
from utils.models import BaseModel, Planta


class Fichero(BaseModel):
    """Fichero Model

    El objeto Fichero tiene los siguientes atributos:
        + nombre (char): Nombre del Fichero
        + desc (text): Descripcion del Fichero
        + archivo (file): Atributo con la referencia al achivo
        + plantas (manytomony): Las plantas que pueden visualizar este fichero.
        + activo (boolean): Estado del Fichero.
    """

    activo = models.BooleanField(
        default=True,
        help_text='Para desactivar la publicación de este fichero, deshabilite esta casilla.'
    )

    archivo = models.FileField(
        upload_to='ficheros/',
        validators=[FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg', ])]
    )

    desc = models.TextField(
        'Descripción',
        blank=True,
        null=True
    )

    nombre = models.CharField(
        max_length=120,
    )

    plantas = models.ManyToManyField(Planta)

    def __str__(self):
        return self.nombre

    @property
    def nombre_archivo(self):
        return os.path.basename(self.archivo.name)

    @property
    def extension_archivo(self):
        name, extension = os.path.splitext(self.archivo.name)
        return extension

firmatec/users/models/users.py
"""User model."""

# Django
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

#Utilities
from utils.models import BaseModel, Planta
# from users import User, Sexo, Civil, Nacionalidades, SistemaSalud, SistemaPrevision, Banco, TipoCta
# atributos, cambiar_clave, codigo, email, rut, sexo, estado_civil, fecha_nac, telefono,
# nacionalidades, domicilio, planta, sistema_salud, sistema_prevision, banco, tipo_cta, cuenta


class Sexo(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este sexo, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Civil(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este estado civil, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Nacionalidades(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True,
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar esta nacionalidad, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class SistemaSalud(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este Sistema de Salud, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class SistemaPrevision(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este estado Sistema de Prevision, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )
    
    def __str__(self):
        return self.nombre

class Banco(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este banco, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )

class TipoCta(models.Model):
    nombre = models.CharField(
        max_length=120,
        unique=True
    )
    status = models.BooleanField(
        default=True,
        help_text='Para desactivar este tipo de cuenta, deshabilite esta casilla.'
    )
    created_date = models.DateTimeField(
            default=timezone.now,
            null=True,
            blank=True
    )


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User, change the username field
    to rut and add some extra fields.
    """
    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    atributos = models.JSONField(blank=True, null=True)

    cambiar_clave = models.BooleanField(
        'Cambiar Clave',
        default=True,
        help_text='Marque esta casilla para que el usuario cambie su clave después de ingresar.'
    )

    codigo = models.CharField(
        'código',
        help_text='Identificador único del sistema de gestión.',
        max_length=6,
        unique=True,
        blank=True,
        null=True
    )

    email = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con este email registrado.'
        }
    )

    planta = models.ManyToManyField(
        Planta,
        help_text='Seleccione una o mas plantas a las que pertenecerá el usuario.'
    )

    rut_regex = RegexValidator(
        regex=r'^[0-9]{7,9}[0-9kK]{1}$',
        message='El RUT debe ser valido. Ingresalo sin puntos ni guiones.'
    )

    rut = models.CharField(
        max_length=12,
        validators=[rut_regex, ],
        unique=True,
        error_messages={
            'unique': 'Ya existe un usuario con este RUT registrado.'
        }
    )

    sexo = models.ForeignKey(Sexo, on_delete=models.PROTECT, null=True, blank=True)

    estado_civil = models.ForeignKey(Civil, on_delete=models.PROTECT, null=True, blank=True)

    fecha_nac = models.DateField(null=True, blank=True)

    telefono_regex = RegexValidator(
        regex=r'\+?1?\d{9,15}$',
        message='El numero de telefono debe ser ingresado en el siguiente formato +999999999. Solo puede ingresar hasta 15 digitos.'
    )

    telefono = models.CharField(
        'Teléfono',
        validators=[telefono_regex, ],
        max_length=15,
        blank=True,
        null=True
    )

    nacionalidades = models.ForeignKey(Nacionalidades, on_delete=models.PROTECT, null=True, blank=True)

    domicilio = models.CharField(
        max_length=200,
        null=True,
        blank=True
    )

    sistema_salud = models.ForeignKey(SistemaSalud, on_delete=models.PROTECT, null=True, blank=True)

    sistema_prevision = models.ForeignKey(SistemaPrevision, on_delete=models.PROTECT, null=True, blank=True)

    banco = models.ForeignKey(Banco, on_delete=models.PROTECT, null=True, blank=True)

    tipo_cta = models.ForeignKey(TipoCta, on_delete=models.PROTECT, null=True, blank=True)

    cuenta = models.CharField(
        'Número de cuenta',
        max_length=30,
        blank=True,
        unique=True,
        null=True
    )

    def __str__(self):
        """Return RUT."""
        return self.rut

    def get_short_name(self):
        """Return RUT."""
        return self.rut

firmatec/utils/views.py
from django.shortcuts import render

# Create your views here.
"""Utils Views. """

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
# Modelo
from ficheros.models import Fichero
from contratos.models import Contrato


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        # Obtengo las plantas del Usuario
        plantas = self.request.user.planta.all()
        # Obtengo los ficheros de las plantas a las que pertenece el usuario
        context['ficheros'] = Fichero.objects.filter(
            plantas__in=plantas, activo=True
        ).distinct()
        # Obtengo los contratos del usuario si no es administrador.
        if not self.request.user.groups.filter(name__in=['Administrador']).exists():
            context['contratos'] = Contrato.objects.filter(
                usuario=self.request.user).order_by('modified')
        else:
            # Obtengo todos los contratos por firmar de todas las plantas a las
            # que pertenece el usuario.
            context['contratos'] = Contrato.objects.filter(
                usuario__planta__in=plantas, estado=Contrato.POR_FIRMAR)

        return context

firmatec/templates/header.html
<div id="header" class="header navbar-default">
  <!-- begin navbar-header -->
  <div class="navbar-header">
    <a href="{% url 'home' %}" class="navbar-brand">
      <span class="logo-firmatec"></span>
    </a>
    <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- end navbar-header -->
  <!-- begin header-nav -->
  <ul class="navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle f-s-14">
        <i class="fa fa-bell"></i>
        <span class="label">5</span>
      </a>
{#      <ul class="dropdown-menu media-list dropdown-menu-right">#}
{#        <li class="dropdown-header">NOTIFICACIONES (5)</li>#}
{#        <li class="media">#}
{#          <a href="javascript:;">#}
{#            <div class="media-left">#}
{#              <i class="fa fa-bug media-object bg-silver-darker"></i>#}
{#            </div>#}
{#            <div class="media-body">#}
{#              <h6 class="media-heading">Server Error Reports <i class="fa fa-exclamation-circle text-danger"></i></h6>#}
{#              <div class="text-muted f-s-11">3 minutes ago</div>#}
{#            </div>#}
{#          </a>#}
{#        </li>#}
{#        <li class="media">#}
{#          <a href="javascript:;">#}
{#            <div class="media-left">#}
{#              <img src="../assets/img/user/user-1.jpg" class="media-object" alt="" />#}
{#              <i class="fab fa-facebook-messenger text-primary media-object-icon"></i>#}
{#            </div>#}
{#            <div class="media-body">#}
{#              <h6 class="media-heading">John Smith</h6>#}
{#              <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>#}
{#              <div class="text-muted f-s-11">25 minutes ago</div>#}
{#            </div>#}
{#          </a>#}
{#        </li>#}
{#        <li class="media">#}
{#          <a href="javascript:;">#}
{#            <div class="media-left">#}
{#              <img src="../assets/img/user/user-2.jpg" class="media-object" alt="" />#}
{#              <i class="fab fa-facebook-messenger text-primary media-object-icon"></i>#}
{#            </div>#}
{#            <div class="media-body">#}
{#              <h6 class="media-heading">Olivia</h6>#}
{#              <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>#}
{#              <div class="text-muted f-s-11">35 minutes ago</div>#}
{#            </div>#}
{#          </a>#}
{#        </li>#}
{#        <li class="media">#}
{#          <a href="javascript:;">#}
{#            <div class="media-left">#}
{#              <i class="fa fa-plus media-object bg-silver-darker"></i>#}
{#            </div>#}
{#            <div class="media-body">#}
{#              <h6 class="media-heading"> New User Registered</h6>#}
{#              <div class="text-muted f-s-11">1 hour ago</div>#}
{#            </div>#}
{#          </a>#}
{#        </li>#}
{#        <li class="media">#}
{#          <a href="javascript:;">#}
{#            <div class="media-left">#}
{#              <i class="fa fa-envelope media-object bg-silver-darker"></i>#}
{#              <i class="fab fa-google text-warning media-object-icon f-s-14"></i>#}
{#            </div>#}
{#            <div class="media-body">#}
{#              <h6 class="media-heading"> New Email From John</h6>#}
{#              <div class="text-muted f-s-11">2 hour ago</div>#}
{#            </div>#}
{#          </a>#}
{#        </li>#}
{#        <li class="dropdown-footer text-center">#}
{#          <a href="javascript:;">View more</a>#}
{#        </li>#}
{#      </ul>#}
    </li>
    <li class="dropdown navbar-user">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fas fa-user-circle fa-fw"></i>
        <span class="d-none d-md-inline">{{ request.user.first_name }}</span> <b class="caret"></b>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="{% url 'users:detail' request.user.id %}" class="dropdown-item">Perfil</a>
        <a href="javascript:;" class="dropdown-item">
          <span class="badge badge-success pull-right">2</span> Mis Contratos</a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'users:logout' %}" class="dropdown-item">Salir</a>
      </div>
    </li>
  </ul>
  <!-- end header navigation right -->
</div>

firmatec/templates/sidebar.html
{% load static %}
{% load user_tags %}
<div id="sidebar" class="sidebar sidebar-transparent">
  <!-- begin sidebar scrollbar -->
  <div data-scrollbar="true" data-height="100%">
    <!-- begin sidebar user -->
    <ul class="nav">
      <li class="nav-profile">
        <a href="javascript:;" data-toggle="nav-profile">
          <div class="cover with-shadow"></div>
          <div class="image">
            {{ request.user.groups.all.first.name|image_profile|safe }}
          </div>
          <div class="info">
            <b class="caret pull-right"></b>
            {{ request.user.first_name}} {{ request.user.last_name }}
            <small>{{ request.user.groups.all.first }}</small>
          </div>
        </a>
      </li>
      <li>
        <ul class="nav nav-profile">
          <li><a href="{% url 'users:detail' request.user.id %}"><i class="fa fa-user"></i> Perfil</a></li>
          <li><a href="javascript:;">
            <i class="fab fa-dochub"></i>
            Mis Contratos <span class="badge pull-right">10</span></a></li>
          {% if request.user.is_staff %}
            <li><a href="{% url "admin:index" %}" target="_blank">
              <i class="fa fa-wrench"></i> Administración</a>
            </li>
          {% endif %}
        </ul>
      </li>
    </ul>
    <!-- end sidebar user -->
    <!-- begin sidebar nav -->
    <ul class="nav">
      <li class="nav-header">Menú</li>
      <li {% if menu_app == 'home' %}class="active"{% endif %}>
        <a href="{% url 'home' %}">
          <i class="fas fa-home"></i>
          <span>Inicio </span>
        </a>
      </li>
      {% if perms.contratos.view_plantilla %}
      <li class="has-sub {% if menu_app == 'contratos' %}active{% endif %}">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-archive"></i>
          <span>Contratos </span>
        </a>
        <ul class="sub-menu">
        {% if perms.contratos.view_plantilla %}
          <li class="has-sub {% if menu_module == 'plantilla' %}expand{% else %}closed{% endif %}">
								<a href="javascript:;">
									<b class="caret"></b>
									Plantillas
								</a>
								<ul class="sub-menu" style="{% if menu_module == 'plantilla' %}display: block;{% else %}display: none;{% endif %}">
									<li {% if menu_module == 'plantilla' and menu_page == 'list' %}class="active"{% endif %}><a href="{% url 'contratos:list-plantilla' %}">Ver Plantillas</a></li>
									<li {% if menu_module == 'plantilla' and menu_page == 'create' %}class="active"{% endif %}><a href="{% url 'contratos:create-plantilla' %}">Crear Plantilla</a></li>
								</ul>
							</li>
        {% endif %}
        {% if perms.contratos.view_contrato %}
          <li class="has-sub {% if menu_module == None %}expand{% else %}closed{% endif %}">
								<a href="javascript:;">
									<b class="caret"></b>
									Contratos
								</a>
								<ul class="sub-menu" style="{% if menu_module == None %}display: block;{% else %}display: none;{% endif %}">
									<li {% if menu_module == None and menu_page == 'list' %}class="active"{% endif %}><a href="{% url 'contratos:list' %}">Ver Contratos</a></li>
								</ul>
							</li>
        {% endif %}
          {% comment %}<li {% if menu_module == 'lista' %}class="active"{% endif %}><a href="ui_general.html">Ver Plantillas </a></li>
        {% if perms.contratos.add_plantilla %}
          <li {% if menu_module == 'lista' %}class="active"{% endif %}><a href="ui_typography.html">Crear Plantilla</a></li>
        {% endif %}{% endcomment %}
        </ul>
      </li>
      {% endif %}
      {% if perms.ficheros.view_fichero %}
      <li class="has-sub {% if menu_app == 'ficheros' %}active{% endif %}">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="far fa-hdd"></i>
          <span>Ficheros Digitales </span>
        </a>
        <ul class="sub-menu">
          <li {% if menu_app == 'ficheros' and menu_page == None %} class="active"{% endif %}><a href="{% url 'ficheros:list' %}">Ver Ficheros </a></li>
        {% if perms.ficheros.add_fichero %}
          <li {% if menu_app == 'ficheros' and menu_page == 'create' %} class="active"{% endif %}><a href="{% url 'ficheros:create' %}">Crear Fichero</a></li>
        {% endif %}
        </ul>
      </li>
      {% endif %}
      {% if perms.users.view_user %}
      <li class="has-sub {% if menu_app == 'users' %}active{% endif %}">
        <a href="javascript:;">
          <b class="caret"></b>
          <i class="fas fa-users"></i>
          <span>Usuarios </span>
        </a>
        <ul class="sub-menu">
          <li {% if menu_app == 'users' and menu_page == None %} class="active"{% endif %}><a href="{% url 'users:list' %}">Ver Usuarios</a></li>
        {% if perms.users.add_user %}
        <li {% if menu_app == 'users' and menu_page == 'create' %} class="active"{% endif %}><a href="{% url 'users:create' %}">Crear Usuario</a></li>
        {% endif %}
        </ul>
      </li>
      {% endif %}
      <!-- begin sidebar minify button -->
      <li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
      <!-- end sidebar minify button -->
    </ul>
    <!-- end sidebar nav -->
  </div>
  <!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>

firmatec/templates/webicons.html
{% load static %}
<!-- Webapp Icons -->
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static  'favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#50b8bc">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="Firmatec">
<meta name="description" content="Firmatec">
<meta name="theme-color" content="#ffffff">
<!-- Favicon Open -->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
<link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">