config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from utils import views

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ficheros/', include(('ficheros.urls', 'ficheros'), namespace='ficheros')),
    path('contratos/', include(('contratos.urls', 'contratos'), namespace='contratos')),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

firmatec/contratos/urls.py
"""Contratos urls."""

#Django
from django.urls import path
from contratos import views


urlpatterns = [
    path(
        route='plantilla/list/',
        view=views.PlantillaListView.as_view(),
        name="list-plantilla"
    ),
    path(
        route='plantilla/create/',
        view=views.create_plantilla,
        name="create-plantilla"
    ),
    path(
        route='<int:plantilla_id>/plantilla/update/',
        view=views.update_plantilla,
        name="update-plantilla"
    ),
    path(
        route='<int:object_id>/plantilla/delete/',
        view=views.delete_plantilla,
        name="delete-plantilla"
    ),
    path(
        route='list/',
        view=views.ContratoListView.as_view(),
        name="list"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.ContratoDetailView.as_view(),
        name="detail"
    ),

]

firmatec/ficheros/urls.py
"""Ficheros urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from ficheros import views


urlpatterns = [
    # Management
    path(
        route='',
        view=views.FicheroListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.FicheroListView.as_view(),
        name='list'
    ),
    path(
        route='<int:fichero_id>/update/',
        view=views.update_fichero,
        name="update"
    ),
    path(
        route='create',
        view=views.create_fichero,
        name="create"
    ),
    path(
        route='<int:fichero_id>/detail/',
        view=views.detail_fichero,
        name="detail"
    ),
    path(
        route='<int:object_id>/delete/',
        view=views.delete_fichero,
        name="delete"
    ),
]

firmatec/urls.py
""" from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
] """
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

firmatec/users/urls.py
"""Users urls."""

# Django
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views


urlpatterns = [
    # Management
    path(
        route='signin/',
        view=views.SignInView.as_view(),
        name='signin'
    ),
    path(
        route='logout/',
        view=auth_views.LogoutView.as_view(next_page='/users/signin/'),
        name='logout'
    ),
    path(
        route='',
        view=views.UserListView.as_view(),
        name='list'
     ),
    path(
        route='<int:planta_id>/',
        view=views.UserListView.as_view(),
        name='list'
    ),
    path(
        route='<int:user_id>/update/',
        view=views.update_user,
        name="update"
    ),
    path(
        route='create',
        view=views.create_user,
        name="create"
    ),
    path(
        route='<int:pk>/detail/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    path(
        route='change_password/',
        view=views.PasswordChangeView.as_view(),
        name='change_password'
    ),
    path(
        route='admin/<int:user_id>/change_password/',
        view=views.admin_change_password,
        name='admin_change_password'
    ),
    path(
        route='<int:user_id>/contrato/',
        view=views.generar_contrato_usuario,
        name='generar_contrato'
    )
]

firmatec/contratos/models/plantillas.py
"""Plantillas model."""

from django.db import models
from django.core.validators import FileExtensionValidator
# Mailmerge
from mailmerge import MailMerge
#Utilities
from utils.models import BaseModel, Planta


class Tipo(BaseModel):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']


class Plantilla(BaseModel):
    activo = models.BooleanField(default=True)
    archivo = models.FileField(
        upload_to='plantillas/',
        validators=[FileExtensionValidator(allowed_extensions=['doc', 'docx', ])]
    )
    nombre = models.CharField(max_length=120)
    plantas = models.ManyToManyField(Planta)
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre

    def codigo(self):
        return str(self.pk).zfill(4)

    @property
    def atributos(self):
        documento = MailMerge(self.archivo)
        atributos = documento.get_merge_fields()
        return atributos

firmatec/contratos/views/contratos.py
"""Contratos views."""

# Django
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.views.generic import ListView, DetailView
# Models
from contratos.models import Contrato, DocumentosContrato


class ContratoListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Contrato List
    Vista para listar todos las contratos según el usuario y plantas.
    """
    model = Contrato
    template_name = "contratos/contrato_list.html"
    paginate_by = 25
    #ordering = ['plantas', 'nombre', ]

    permission_required = 'contratos.view_contrato'
    raise_exception = True

    def get_queryset(self):
        search = self.request.GET.get('q')
        planta = self.kwargs.get('planta_id', None)

        if planta == '':
            planta = None

        if search:
            # Si el usuario no administrador se despliegan todos los contratos
            # de las plantas a las que pertenece el usuario, según el critero de busqueda.
            if not self.request.user.groups.filter(name__in=['Administrador', ]).exists():
                queryset = super(ContratoListView, self).get_queryset().filter(
                    Q(usuario__planta__in=self.request.user.planta.all()),
                    Q(usuario__first_name__icontains=search),
                    Q(usuario__last_name__icontains=search)
                ).distinct()
            else:
                # Si el usuario es administrador se despliegan todos las plantillas
                # segun el critero de busqueda.
                queryset = super(ContratoListView, self).get_queryset().filter(
                    Q(usuario__first_name__icontains=search),
                    Q(usuario__last_name__icontains=search)
                ).distinct()
        else:
            # Si el usuario no es administrador, se despliegan los contrtatos
            # de las plantas a las que pertenece el usuario.
            if not self.request.user.groups.filter(name__in=['Administrador']).exists():
                queryset = super(ContratoListView, self).get_queryset().filter(
                    Q(usuario__planta__in=self.request.user.planta.all()),
                ).distinct()
            else:
                # Si el usuario es administrador, se despliegan todos los contratos.
                if planta is None:
                    queryset = super(ContratoListView, self).get_queryset()
                else:
                    # Si recibe la planta, solo muestra las plantillas que pertenecen a esa planta.
                    queryset = super(ContratoListView, self).get_queryset().filter(
                        Q(usuario__planta__in=self.request.user.planta.all())
                    ).distinct()

        return queryset


class ContratoDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Contrato
    template_name = "contratos/contrato_detail.html"
    context_object_name = "contrato"

    permission_required = 'contratos.view_contrato'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super(ContratoDetailView, self).get_context_data(**kwargs)
        # Solo el administrador puede ver el contrato de otro usuario.
        if not self.request.user.groups.filter(name__in=['Administrador', 'Administrador Contratos', ]).exists():
            if not self.object.usuario == self.request.user:
                raise Http404

        # Obtengo todos los documentos del contrato
        documentos = DocumentosContrato.objects.filter(contrato=self.object.id)
        context['documentos'] = documentos

        return context

firmatec/contratos/views/plantillas.py
"""Plantillas views."""

# Django
from datetime import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q, ProtectedError
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView
# Models
from contratos.models import Plantilla
from utils.models import Planta
# From
from contratos.forms import CrearPlantillaForm, ActualizarPlantillaForm


class PlantillaListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Plantilla List
    Vista para listar todos las plantilla según el usuario y sus las plantas
    relacionadas.
    """
    model = Plantilla
    template_name = "contratos/plantilla_list.html"
    paginate_by = 25
    ordering = ['plantas', 'nombre', ]

    permission_required = 'contratos.view_plantilla'
    raise_exception = True

    def get_queryset(self):
        search = self.request.GET.get('q')
        planta = self.kwargs.get('planta_id', None)

        if planta == '':
            planta = None

        if search:
            # Si el usuario no se administrador se despliegan las plantillas en estado activo
            # de las plantas a las que pertenece el usuario, según el critero de busqueda.
            if not self.request.user.groups.filter(name__in=['Administrador', ]).exists():
                queryset = super(PlantillaListView, self).get_queryset().filter(
                    Q(activo=True),
                    Q(plantas__in=self.request.user.planta.all()),
                    Q(nombre__icontains=search)
                ).distinct()
            else:
                # Si el usuario es administrador se despliegan todos las plantillas
                # segun el critero de busqueda.
                queryset = super(PlantillaListView, self).get_queryset().filter(
                    Q(nombre__icontains=search)
                ).distinct()
        else:
            # Si el usuario no es administrador, se despliegan las plantillas en estado
            # activo de las plantas a las que pertenece el usuario.
            if not self.request.user.groups.filter(name__in=['Administrador']).exists():
                queryset = super(PlantillaListView, self).get_queryset().filter(
                    Q(activo=True),
                    Q(plantas__in=self.request.user.planta.all())
                ).distinct()
            else:
                # Si el usuario es administrador, se despliegan todos las plantillas.
                if planta is None:
                    queryset = super(PlantillaListView, self).get_queryset()
                else:
                    # Si recibe la planta, solo muestra las plantillas que pertenecen a esa planta.
                    queryset = super(PlantillaListView, self).get_queryset().filter(
                        Q(plantas=planta)
                    ).distinct()

        return queryset


@login_required
@permission_required('contratos.change_plantilla', raise_exception=True)
def update_plantilla(request, plantilla_id):

    plantilla = get_object_or_404(Plantilla, pk=plantilla_id)

    # Se obtienen las plantas del usuario.
    try:
        plantas_usuario = Planta.objects.values_list('id', flat=True).filter(user=request.user)
    except:
        plantas_usuario = ''

    if request.method == 'POST':

        form = ActualizarPlantillaForm(data=request.POST, instance=plantilla, files=request.FILES, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Plantilla actualizada exitosamente')
            page = request.GET.get('page')
            if page != '':
                response = redirect('contratos:list-plantilla')
                response['Location'] += '?page=' + page
                return response
            else:
                return redirect('contratos:list-plantilla')
        else:
            messages.error(request, 'Por favor revise el formulario e intentelo de nuevo.')
    else:
        form = ActualizarPlantillaForm(instance=plantilla,
                                       initial={'plantas': list(plantas_usuario), },
                                       user=request.user)

    return render(
        request=request,
        template_name='contratos/plantilla_create.html',
        context={
            'plantilla': plantilla,
            'form': form
        })

@login_required
@permission_required('contratos.add_plantilla', raise_exception=True)
def create_plantilla(request):
    if request.method == 'POST':

        form = CrearPlantillaForm(data=request.POST, files=request.FILES, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Plantilla Creada Exitosamente')

            return redirect('contratos:list-plantilla')
        else:
            messages.error(request, 'Por favor revise el formulario e intentelo de nuevo.')
    else:
        form = CrearPlantillaForm(user=request.user)

    return render(request, 'contratos/plantilla_create.html', {
        'form': form,
    })


@login_required
def delete_plantilla(request, object_id, template_name='contratos/plantilla_delete.html'):
    data = dict()
    object = get_object_or_404(Plantilla, pk=object_id)
    if request.method == 'POST':
        try:
            object.delete()
            messages.success(request, 'Plantilla eliminada exitosamente')
        except ProtectedError:
            messages.error(request, 'La plantilla no se pudo eliminar.')
            return redirect('contratos:update-plantilla', object_id)

        return redirect('contratos:list-plantilla')

    context = {'object': object}
    data['html_form'] = render_to_string(
        template_name,
        context,
        request=request
    )
    return JsonResponse(data)

firmatec/utils/views.py
from django.shortcuts import render

# Create your views here.
"""Utils Views. """

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
# Modelo
from ficheros.models import Fichero
from contratos.models import Contrato


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        # Obtengo las plantas del Usuario
        plantas = self.request.user.planta.all()
        # Obtengo los ficheros de las plantas a las que pertenece el usuario
        context['ficheros'] = Fichero.objects.filter(
            plantas__in=plantas, activo=True
        ).distinct()
        # Obtengo los contratos del usuario si no es administrador.
        if not self.request.user.groups.filter(name__in=['Administrador']).exists():
            context['contratos'] = Contrato.objects.filter(
                usuario=self.request.user).order_by('modified')
        else:
            # Obtengo todos los contratos por firmar de todas las plantas a las
            # que pertenece el usuario.
            context['contratos'] = Contrato.objects.filter(
                usuario__planta__in=plantas, estado=Contrato.POR_FIRMAR)

        return context

firmatec/templates/contratos/contrato_list.html
{% extends 'base.html' %}
{% load static %}
{% load contratos_tags %}
{% block page_title %}Contratos{% endblock %}
{% block styles %}
.text-name {
  margin-bottom: 0em;
  font-weight: bold;
  font-size: medium;
}

.text-desc {
  font-style: italic;
  margin-top:-0.1em;
  padding-left: 0.1em;
  font-size: small;
}

.estado-fichero{
  text-align: center;
  vertical-align: middle;
}
.centrar{
    align-items: center;
    justify-content: center;
}
.pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover {
    background: #00acac !important;
    border-color: #00acac !important;
    color: #fff;
}
{% endblock %}
{% block content %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
  <li class="breadcrumb-item"><a href="javascript:;">Inicio</a></li>
  <li class="breadcrumb-item"><a href="javascript:;">Contratos</a></li>
  <li class="breadcrumb-item active">Listado</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Contratos <small>Listado</small></h1>
<!-- end page-header -->

<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
    </div>
    <h4 class="panel-title">Todos los contratos</h4>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
          <tr>
              <th class="text-center" width="5%">#</th>
              <th class="text-center" width="30%">Contratos</th>
              <th class="text-center" width="25%">Planta</th>
              <th class="text-center" width="20%">Estado</th>
              <th class="text-center" width="20%">Actualizado</th>
          </tr>
      </thead>
      <tbody>
      {% for obj in object_list  %}
          <tr>
            <td class="text-right">{{ forloop.counter }}.</td>
            <td>
                <a href="{% url 'contratos:detail' obj.id %}?page={{ request.GET.page }}">
                    <span class="text text-success">
                        {{ obj.usuario.first_name|title }} {{ obj.usuario.last_name|title }}
                    </span>
                </a>
            </td>
            <td class="text-center">
              {{ obj.usuario.planta.first }}
            </td>
            <td class="text-center">
              {{ obj.estado|estado_contrato|safe }}
            </td>
            <td>
               <p class="text-center">
                  {{ obj.modified|date:'d/M/Y' }} <br>
               </p>
            </td>
          </tr>
      {% empty %}
        <tr><td colspan="5">
          <div class="text-center">No hay contratos generados.</div>
        </td></tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
     {% if is_paginated %}
      <!-- pagination -->
     <ul class="pagination centrar">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a href="{{ request.path }}?{% if filtro %}q={{ filtro }}&{% endif %}page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
           class="page-link">«</a>
      </li>
      {% for page in page_obj.paginator.page_range %}
          {% if page_obj.number|add:'-5' <= page and page_obj.number|add:'5' >= page%}
            <li class="page-item {% if page_obj.number == page %}active{% endif %}">
              <a href="{{ request.path }}?{% if filtro %}q={{ filtro }}&{% endif %}page={{ page }}"
                 class="page-link">{{ page }}</a>
            </li>
          {% endif %}
      {% endfor %}
      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a href="{{ request.path }}?{% if filtro %}q={{ filtro }}&{% endif %}page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
           class="page-link">»</a>
      </li>
    </ul>
      {% if page_obj.paginator.num_pages > 5 %}
      <ul class="pager m-t-0 m-b-0">
        <li class="page-item previous {% if not page_obj.has_previous %}disabled{% endif %}">
          <a href="{{ request.path }}?page=1" class="page-link">← Primero</a></li>
        <li class="page-item next {% if not page_obj.has_next %}disabled{% endif %}">
          <a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}" class="page-link">Último →</a></li>
      </ul>
     {% endif %}
  {% endif %}

  </div>
</div>
<div class="modal fade" id="modal-plantilla">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
<!-- end panel -->
{% endblock %}
{% block scripts %}

      $('.btn-view-fichero').on('click', function(e){
        e.preventDefault();
        var id = $(this).data('id');
        console.log('fichero_id', 'id');
        var URL = '/ficheros/'+id+'/detail/';

        console.log('URL', URL);

        $.ajax({
              url: URL,
              type: 'get',
              dataType: 'json',
              beforeSend: function () {
                $("#modal-fichero").modal("show");
              },
              success: function (data) {
                  $("#modal-fichero .modal-content").html(data.html_form);
              }
            });
    });

  {% if messages %}
        console.log('mensajes');
        {% for mensaje in messages %}
            console.log("{{ mensaje.tags}}"+" "+"{{ mensaje }}");
            {% if mensaje.tags == 'success' %}
              iziToast.success({
                  message: '{{ mensaje }}',
                  position: 'topRight',
              });
            {% elif mensaje.tags == 'error' %}
              iziToast.error({
                  message: '{{ mensaje }}',
                  position: 'topRight',
              });
            {% endif %}
        {% endfor %}

    {% endif %}
{% endblock %}

firmatec/templates/contratos/plantilla_create.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_title %}Contratos{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'admin/assets/plugins/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
  <li class="breadcrumb-item"><a href="javascript:;">Inicio</a></li>
  <li class="breadcrumb-item"><a href="{% url 'contratos:list-plantilla' %}">Plantillas</a></li>
  <li class="breadcrumb-item active">{% if plantilla %}{{ plantilla.id }}{% else %}Nueva{% endif %}</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Plantilla <small>{% if usuario %}Editar{% else %}Nueva{% endif %}</small></h1>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
      <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
    </div>
    <h4 class="panel-title">
      {% if plantilla %}{{ plantilla.nombre|upper }}{% else %}Plantilla Nueva{% endif %}</h4>
  </div>
  <div class="panel-body">

    {% if form.non_field_errors%}
      <div class="alert alert-danger fade show">
        <span class="close" data-dismiss="alert">×</span>
        <h5><i class="fa fa-exclamation-triangle"></i> Revisa el fomulario!</h5>
        {% for err in form.non_field_errors %}{{ err }}<br>{% endfor %}
      </div>
    {% else %}
      <div class="alert alert-danger fade show" id="msgbox" style="display: none;">
        <span class="close" data-dismiss="alert">×</span>
        <span>
          <strong><i class="icon fa fa-exclamation-triangle text-danger pr-1"></i>
            <span id="num-errors"></span></strong>
          Revisa el formulario, sigue las instrucciones y completa los datos.</span>
      </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data" autocomplete="off" novalidate>
      {% csrf_token  %}
      {% include 'basic_form.html' with form=form %}
      <br/>
      <div class="form-group row m-b-0">
        <div class="col-md-4 col-sm-4">
          {% if plantilla and perms.ficheros.delete_fichero %}
            <button type="button" id="btn-delete" class="btn btn-danger">Eliminar</button>
          {% endif %}
        </div>
        <div class="col-md-8 col-sm-8 text-right">
          <a href="{% url 'contratos:list-plantilla' %}?page={{ request.GET.page }}" class="btn btn-default">Cancelar</a>
          <button type="submit" class="btn btn-success" id="btn-guardar">Guardar</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- end panel -->
<div class="modal fade" id="modal-plantilla">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>
{% endblock %}
{% block librerias %}
    <script src="{% static 'admin/assets/plugins/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'admin/assets/plugins/bootstrap-select/js/i18n/defaults-es_CL.min.js' %}"></script>
    <!-- jquery validation -->
    <script src="{% static "admin/assets/plugins/jquery-validation/dist/jquery.validate.min.js" %}"></script>
  <script src="{% static "admin/assets/plugins/jquery-validation/dist/additional-methods.min.js" %}"></script>
    <script src="{% static "admin/assets/plugins/jquery-validation/dist/localization/messages_es_PE.min.js" %}"></script>
{% endblock %}
{% block scripts %}
  var enviando = false;
  //Submit form
  $('#btn-guardar').on('click', function(e){
      $(this).prop('disabled', true);
      $(this).addClass('disabled');

      e.preventDefault();

      var $form = $('form');
      var validator = $form.validate({
          ignore: "",
          errorClass: "is-invalid",
          validClass: "is-valid",
          errorElement: 'div',
          errorPlacement: function ( error, element ) {
            error.addClass("invalid-feedback");

            if(element.prop("type") === "checkbox") {
              error.insertAfter(element.parent("label"));
            }else{
              error.insertAfter(element);
            }

            // Add the span element, if doesn't exists, and apply the icon classes to it.
            if (!element.next("div")[0]) {
              $( "<div class='glyphicon glyphicon-remove form-control-feedback'></div>" ).insertAfter( element );
            }
          },
          wrapper: "",
          rules: {
                  nombre: "required",
                  desc: "required",

                  archivo: {
                  {% if not plantilla %}
                    required: true,
                  {% endif %}
                    accept: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                    },

                  plantas: "required",
                },
                messages: {
                  nombre: "Ingresa el nombre del fichero digital.",
                  archivo: {
                    {% if not plantilla %}
                      required: "Selecciona un archivo.",
                    {% endif %}
                      accept: "Solo se aceptan archivos Word."
                  },
                  plantas: "Selecciona al menos una planta."
          },
          showErrors: function(errorMap, errorList) {
              console.log('show messages', errorList.length);
              if(errorList.length){
                  $('#msgbox').show('slow');
                  $("#num-errors").html("Tienes "+ this.numberOfInvalids() + " errores.");

                  this.defaultShowErrors();
                  console.log('Errores', errorMap, errorList);
              }
        }
      });

      if(validator.form()){
          if(!enviando){
              enviando = true;
              $(this).html('<i class="fa fa-spinner fa-pulse margin-r-5"></i> Guardando...');
              $form.submit();
          }else{
              console.log("El formulario ya se esta enviando...");
          }
      }else{
          console.log('Error en el formulario.');
          $(this).removeClass('disabled');
          $(this).prop('disabled', false);
      }

  })

{% if plantilla and perms.plantilla.delete_plantilla %}
  var deleteURL = "{% url 'contratos:delete-plantilla' plantilla.id %}";

  $('#btn-delete').on('click', function(e){
      e.preventDefault();

      console.log('click delete object');
      console.log(deleteURL);

      $.ajax({
        url: deleteURL,
        type: 'get',
        dataType: 'json',
        beforeSend: function () {
          $("#modal-plantilla").modal("show");
        },
        success: function (data) {
            $("#modal-plantilla .modal-content").html(data.html_form);
        }
      });
  });
{% endif %}

{% if messages %}
      console.log('mensajes');
      {% for mensaje in messages %}
          console.log("{{ mensaje.tags}}"+" "+"{{ mensaje }}");
          {% if mensaje.tags == 'success' %}
            iziToast.success({
                message: '{{ mensaje }}',
                position: 'topRight',
            });
          {% elif mensaje.tags == 'error' %}
            iziToast.error({
                message: '{{ mensaje }}',
                position: 'topRight',
            });
          {% endif %}
      {% endfor %}

  {% endif %}
{% endblock %}

firmatec/templates/contratos/plantilla_delete.html
<form method="post" action="{% url 'contratos:delete-plantilla' object.id %}">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Mensaje de Confirmación</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="form-group text-center">
        <p class="font-13">¿Esta seguro que desea eliminar la plantilla de contrato?</p>
        <h4><strong>{{ object.nombre }}</strong></h4>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-danger m-r-5">Eliminar</button>
  </div>
</form>